name: Deploy

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -H slab1.ethz.ch >> ~/.ssh/known_hosts

      - name: Deploy
        run: rsync -aPz dist/ dschroeder@slab1.ethz.ch:homepage
